name: GitHub Changelog RSS Feed
on:
  schedule:
    # At every :30
    - cron: 30 * * * *

  workflow_dispatch:
jobs:
  github-changelog:
    name: github-changelog-rss
    runs-on: ubuntu-latest
    steps:
      - uses: guilhem/rss-issues-action@0.4.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          feed: "https://github.blog/changelog/feed/"
          prefix: "[GitHub]"
          characterLimit: "255"
          dry-run: "false"
          lastTime: "92h"
          labels: "github"
